name: chck prtmnt
on:
  push:
    branches: main
  pull_request:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install browsers
        run: playwright install --with-deps
      - name: Run Playwright tests
        run: python chck.py
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: chck
          path: ./
          retention-days: 1
